#R code
library(marray)
library(gplots)
t <- read.table('data/LanddisMatrix',header=1,row.names=1)
t <- t(t(t))
mcol <- maPalette(low="blue", mid="white", high="red")
png('graph/LandDisHeatMap.png',res=1200,height=7200,width=7200)
#heatmap.2(t,col=mcol,dendrogram='both',trace="none",labCol=F,labRow=F,keysize=1,density.info='none')
hm <- heatmap.2(t,col=mcol,Rowv=F,Colv=F,dendrogram='none',trace="none",labCol=F,keysize=1,density.info='none',cexRow=0.05)
dev.off()

#t <- read.table('data/MutPotdisMatrix',header=1,row.names=1)
#t <- t(t(t))
#mcol <- maPalette(low="blue", mid="white", high="red")
#png('graph/MutPotDisHeatMap.png',res=1200,height=7200,width=7200)
##heatmap.2(t,col=mcol,dendrogram='both',trace="none",labCol=F,labRow=F,keysize=1,density.info='none')
#hm <- heatmap.2(t,col=mcol,Rowv=F,Colv=F,dendrogram='none',trace="none",labCol=F,keysize=1,density.info='none',cexRow=0.05)
#dev.off()
